### ISSUE TITLE
User Story #2: Login and Sign-Up Pages

### ISSUE THREAD

**Issue by nada-gz** [Sammany1/Task-Tracking-Tool#11]
As a user, I want to access the login and sign-up pages to input my information.

Description:

As a user: I want to access a form to either log in or sign up.
I want to: Enter my information and submit it.
So that: I can move to the home page (for now, no authentication or validation).

Acceptance Criteria:

Login Page:
- Includes inputs for "Email" and "Password."
- A Login Button to go to the main page.

Sign-Up Page:
- Includes inputs for "Full Name", "Email", "Password", and "Confirm Password".
- A Submit Button to go to the main page.

Both pages:
- Redirect to the home page upon clicking "Login" / "Sign-Up".
- Are styled consistently.

Related Issues:

#3 : Login Page.
#5 : Sign-Up Page.

**Comment by omar813** [comment]
Completed the implementation of Login and Sign-Up pages.
